language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

addons:
  apt:
    packages:
      - xvfb
      - oracle-java8-installer

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start

before_install:
  - export M2_HOME=/usr/local/maven
  - export MAVEN_OPTS="-Xms256m -Xmx1024m -XX:MaxPermSize=512m -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Dmaven.junit.fork=true -Dmaven.junit.jvmargs=-Xmx2048m -Dmaven.compile.fork=true -Dmaven.javadoc.skip=true"

after_success:
  - bash <(curl -s https://codecov.io/bash)
