language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

addons:
  apt:
    packages:
      - xvfb
      - oracle-java8-installer

before_install:
  - export MAVEN_OPTS="-Xms256m -Xmx1024m -XX:MaxPermSize=512m -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Dmaven.junit.fork=true -Dmaven.compile.fork=true -Dmaven.javadoc.skip=true"
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start

script:
  - mvn clean verify

after_success:
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r coverage-all/target/coverage-report/coverage-report.xml
