spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/ic
    username: ic
    password: ic
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

spring.thymeleaf:
  cache: false
  mode: LEGACYHTML5

server:
  tomcat.accesslog.enabled: true
  port: 9009

security.user.password: test

logging:
  level:
    ROOT: ERROR
    org.springframework.web: ERROR
    org.springframework.boot.autoconfigure.security: INFO
    org.apache.catalina.filters: TRACE
    org.apache.http: DEBUG
    org.apache.http.wire: DEBUG
    javax.mail: ERROR
    pl.pamsoft: DEBUG
  file: imapcloud.log

ic:
  recoveries.folder: ./recoveries/
